openapi: 3.0.3
info:
  title: Agenda API
  description: API for managing events, time slots, and user authentication
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development server

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Token
      description: Bearer token authentication

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email

    Event:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        organizerId:
          type: integer
        selectionType:
          type: string
          enum: [SINGLE, MULTIPLE]

    TimeSlot:
      type: object
      properties:
        id:
          type: integer
        eventId:
          type: integer
        startTime:
          type: string
          format: date-time
        durationInMinutes:
          type: integer

    Participant:
      type: object
      properties:
        id:
          type: integer
        user:
          $ref: '#/components/schemas/User'
        slot:
          $ref: '#/components/schemas/TimeSlot'

    UserInput:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: "Paul Atreides"
        email:
          type: string
          format: email
          example: "paul@atreides.com"
        password:
          type: string
          example: "muadib"

    EventInput:
      type: object
      required:
        - title
        - description
        - selectionType
      properties:
        title:
          type: string
          example: "Arrakis Sandstorm Meeting"
        description:
          type: string
          example: "Discuss plans for the Fremen alliance"
        selectionType:
          type: string
          enum: [SINGLE, MULTIPLE]
          example: "SINGLE"

    TimeSlotInput:
      type: object
      required:
        - startTime
        - durationInMinutes
      properties:
        startTime:
          type: string
          format: date-time
          example: "2024-10-10T17:00:00"
        durationInMinutes:
          type: integer
          example: 60

    UserCreateTokenInputModel:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "paul@atreides.com"
        password:
          type: string
          example: "muadib"

    UserCreateTokenOutputModel:
      type: object
      properties:
        token:
          type: string
          example: "n8AVqGnzbGkvDPryo8t14kWz6KfQIxygL3AH-HHMS28="

    UserHomeOutputModel:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
          format: email

    Problem:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string

paths:
  /api/status/hostname:
    get:
      tags:
        - Status
      summary: Get hostname
      description: Returns the server hostname from environment variable
      operationId: getStatusHostname
      responses:
        '200':
          description: Server hostname
          content:
            text/plain:
              schema:
                type: string

  /api/status/ip:
    get:
      tags:
        - Status
      summary: Get IP address
      description: Returns the server IP address
      operationId: getStatusIp
      responses:
        '200':
          description: Server IP address
          content:
            text/plain:
              schema:
                type: string

  /api/users:
    post:
      tags:
        - Users
      summary: Create a new user
      description: Register a new user in the system
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInput'
      responses:
        '201':
          description: User created successfully
          headers:
            Location:
              schema:
                type: string
              description: URI of the created user
              example: "/api/users/1"
        '400':
          description: Bad request (email already in use or insecure password)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'

  /api/users/token:
    post:
      tags:
        - Users
      summary: Create authentication token
      description: Login and obtain an authentication token
      operationId: createToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreateTokenInputModel'
      responses:
        '200':
          description: Token created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserCreateTokenOutputModel'
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'

  /api/logout:
    post:
      tags:
        - Users
      summary: Logout user
      description: Revoke the current authentication token
      operationId: logout
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully logged out
        '401':
          description: Unauthorized

  /api/me:
    get:
      tags:
        - Users
      summary: Get authenticated user information
      description: Returns the profile information of the currently authenticated user
      operationId: getUserHome
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserHomeOutputModel'
        '401':
          description: Unauthorized

  /api/events:
    get:
      tags:
        - Events
      summary: Get all events
      description: Returns a list of all events in the system
      operationId: getAllEvents
      responses:
        '200':
          description: List of events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'

    post:
      tags:
        - Events
      summary: Create a new event
      description: Create a new event with the authenticated user as organizer
      operationId: createEvent
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventInput'
      responses:
        '200':
          description: Event created successfully
          content:
            application/json:
              schema:
                type: integer
                description: Event ID
        '401':
          description: Unauthorized
        '404':
          description: Participant not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'

  /api/events/{eventId}:
    get:
      tags:
        - Events
      summary: Get event by ID
      description: Returns detailed information about a specific event
      operationId: getEventById
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
          description: Event ID
      responses:
        '200':
          description: Event details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '404':
          description: Event not found

  /api/events/{eventId}/timeslots:
    get:
      tags:
        - TimeSlots
      summary: Get time slots for an event
      description: Returns all time slots for a specific event
      operationId: getEventTimeSlots
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
          description: Event ID
      responses:
        '200':
          description: List of time slots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TimeSlot'
        '404':
          description: Event not found

    post:
      tags:
        - TimeSlots
      summary: Create a free time slot
      description: Create a new available time slot for an event
      operationId: createFreeTimeSlot
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
          description: Event ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeSlotInput'
      responses:
        '201':
          description: Time slot created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSlot'
        '404':
          description: Event not found

  /api/events/{eventId}/timeslots/{timeSlotId}/participants:
    get:
      tags:
        - TimeSlots
      summary: Get participants in a time slot
      description: Returns all participants for a specific time slot (only for MULTIPLE selection type)
      operationId: getParticipantsInTimeSlot
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
          description: Event ID
        - name: timeSlotId
          in: path
          required: true
          schema:
            type: integer
          description: Time slot ID
      responses:
        '200':
          description: List of participants
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Participant'
        '400':
          description: Time slot does not support multiple participants (SINGLE type)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Time slot not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'

    put:
      tags:
        - TimeSlots
      summary: Add participant to time slot
      description: Add the authenticated user as a participant to a specific time slot
      operationId: addParticipantToTimeSlot
      security:
        - BearerAuth: []
      parameters:
        - name: eventId
          in: path
          required: true
          schema:
            type: integer
          description: Event ID
        - name: timeSlotId
          in: path
          required: true
          schema:
            type: integer
          description: Time slot ID
      responses:
        '200':
          description: Participant added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSlot'
        '401':
          description: Unauthorized
        '404':
          description: Time slot, user, or event not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '409':
          description: Conflict (time slot already allocated or user already participant)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
