FROM nginx

# Copy nginx configuration
COPY ./lesson41-nginx/nginx.conf /etc/nginx/nginx.conf


# Copy frontend bundle to nginx web root
COPY ./lesson33-agenda-frontend/dist /usr/share/nginx/html

EXPOSE 4000

CMD ["nginx", "-g", "daemon off;"]
